spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  packages-to-scan: com.example.solex_backend.controller

openroute-service:
  api-key: ${OPENROUTE_API_KEY:}