spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  packages-to-scan: com.example.solex_backend.controller

openroute-service:
  api-key: ${OPENROUTE_API_KEY:}